### ISSUE TITLE
Wrapup + README

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/banjo-challenge#11]
# Motivation
We ware almost done but there is still the Writeup that needs to be completed via the README and the fixing of a few minor issues.

# Tasks
- [x] Write Up README.
- [x] On README add notes about the need to add reasonable property addresses and no use of apostrophies in text fields. 
- [x] Fix minor visual error of not showing descriptions in the all other properties list.
