### ISSUE TITLE
User can login/out

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/banjo-challenge#5]
# Motivation
Now that we can create an account we want to be able to login and logout. When a user logs in, they will recieve a JWT that will validate their session for a set time so that the user will not need to constantly relog in if they have already done so, and then when the user logs out, the local storage will be cleared.

# Tasks
- [x] Create a new component for logging in.
- [x] Create another component that switches between the login page and the account creation page. 
- [x] Be able to switch between create user and login apps. 
- [x] Be able to authenticate that you have the correct credentials
- [x] Be able to get back a session token from a login and store it in localStorage.
- [x] Be able with a JWT login automatically.
- [x] When logged in, have a page that greets the user.
- [x] Be able to logout by clearing the credentials.
