### ISSUE TITLE
User can GET/POST/PUT/DELETE properties

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/banjo-challenge#7]
# Motivation
Now that we can login, we want to be able to get, create, edit and delete properties from our specific user. 

# Tasks
- [x] Split up the API into routes.
- [x] Maintain structure of being able to modularize and scale the API.
- [x] Create a new table of properties.
- [x] Create GET/POST/PUT/DELETE methods for properties.
- [x] Be able to get the list of your properties.
- [x] Be able to create a property.
- [x] Be able to edit a property.
- [x] Be able to toggle between editting and not for a property.
- [x] Be able to delete a property.
