### ISSUE TITLE
User can spot properties for sale on Google Maps

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/banjo-challenge#9]
# Motivation
Now that we can create a user, login/logout and CRUD a list of your own properties, we want to be able to be able to implement one of the final parts to our project, which is to be able to see all the properties that are available on google maps.

# Task Implementation
- [x] Get a Google Maps API Key and integrate it into the project.
- [x] add packages to be able to get a google map onto the project.
- [x] Be able to view the basic google map.
- [x] Be able to see all the list of all properties for sale next to the map.
- [x] Be able to see markers above all the properties on the map.
- - [x] Include this for your own properties too.
- [x] Be able to hover over the marker to see information about it.
- [x] Be able to delete a marker by deleting your own property.
- [x] Be able to edit a marker's tooltip by editing your own property.
- [x] Be able to add a marker by adding your own property.
- [x] Deploy to Heroku.
